dist: xenial
language: java

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar"

before_cache:
  - rm -rf $HOME/.m2/repository/com/twa/flights

install:
- curl -o $HOME/.m2/settings.xml
  https://gist.githubusercontent.com/andres-sacco/c23c779d64ee1834c4fe5e6c556f24ab/raw/992c4901ac0facdbc584598851deedf630acfacd/settings.xml

script:
  - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

jdk: 
  - openjdk11

os:
  - linux

