version: '3.0'
services:      
  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:8.0.27
    #image: mysql:5.7.28
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
     - 3310:3306

  api-clusters-db:
    container_name: api-clusters-db
    image: redis:alpine
    platform: linux/amd64
    restart: always
    ports:
     - 6079:6379
     
  api-pricing-db:
    container_name: api-pricing-db
    image: mysql:8.0.27
    #image: mysql:5.7.28
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_pricing'
      MYSQL_ROOT_PASSWORD: 'muppet'        
    ports:
     - 3311:3306
