management:
  health.db.enabled: false
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8070
  servlet:
    context-path: /api/flights/provider/alpha

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

spring:
  profiles:
    active: chaos-monkey
    
connector:
   catalog:
      host: localhost:6070
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000

chaos:
  monkey:
    enabled: false
    assaults:
      exceptionsActive: false
      latencyActive: false