pipeline {
    agent any
    tools {
        maven 'Maven 3.8.6'
    }
    stages {

            stage('Compile') {
                steps {
                    dir('api-catalog') {
                        sh 'mvn clean compile'
                    }
                }

            } 
            stage('Unit Test') {
                steps {
                    dir('api-catalog') {
                        sh 'mvn test'
                    }
                }
            }
            stage('Quality') {
                steps {
                    dir('api-catalog') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=api_catalog -Dsonar.host.url=http://sonar:9000 -Dsonar.login=squ_99c7237a396e5003ec4b3fbbe520509d9301b61b'
                    }
                }
            }
            stage('Package') {
                steps {
                    dir('api-catalog') {
                        sh 'mvn -B -DskipTests package'
                    }
                }
            }
    }
}
