pipeline {
    agent any
    tools {
        maven 'Maven 3.8.6'
    }
    stages {

            stage('Compile') {
                steps {
                    dir('api-clusters') {
                        sh 'mvn clean compile'
                    }
                }

            } 
            stage('Unit Test') {
                steps {
                    dir('api-clusters') {
                        sh 'mvn test'
                    }
                }
            }
            stage('Architecture Test') {
                steps {
                    dir('api-clusters') {
                        sh 'mvn test -P AT -Dmaven.test.skip=true'
                    }
                }
            }

            stage('Quality') {
                steps {
                    dir('api-clusters') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=api_clusters -Dsonar.host.url=http://sonar:9000 -Dsonar.login=squ_245ff33d5a47b0b120f711bbaabbe7e7e9f3cb1d'
                    }
                }
            }
            stage('Package') {
                steps {
                    dir('api-clusters') {
                        sh 'mvn -B -DskipTests package'
                    }
                }
            }
    }
}
